switch1:
  hostname: 192.168.12.247
  data:
    vlans:
      - id: 100
        name: PC
        members: 1/1/10
        ip: 192.168.100.254/24
    interfaces:
      - name: 1/1/1
        ip_address: 10.0.0.0
        subnet_mask: 31
        vlan_id: 10
        peer: SW2
        peer_if: 1/1/1
      - name: 1/1/8
        ip_address: 10.0.0.2
        subnet_mask: 31
        vlan_id: 20
        peer: SW2
        peer_if: 1/1/8
      - name: 1/1/3
        ip_address: 10.0.0.4
        subnet_mask: 31
        vlan_id: 30
        peer: SW3
        peer_if: 1/1/3
      - name: 1/1/4
        ip_address: 10.0.0.6
        subnet_mask: 31
        vlan_id: 40
        peer: SW3
        peer_if: 1/1/4

switch2:
  hostname: 192.168.12.248
  data:
    vlans:
      - id: 120
        name: PC
        members: 1/1/10
        ip: 192.168.120.254/24
    interfaces:
      - name: 1/1/1
        ip_address: 10.0.0.1
        subnet_mask: 31
        vlan_id: 10
        peer: SW1
        peer_if: 1/1/1
      - name: 1/1/8
        ip_address: 10.0.0.3
        subnet_mask: 31
        vlan_id: 20
        peer: SW1
        peer_if: 1/1/8
      - name: 1/1/3
        ip_address: 10.0.0.8
        subnet_mask: 31
        vlan_id: 50
        peer: SW3
        peer_if: 1/1/1
      - name: 1/1/4
        ip_address: 10.0.0.10
        subnet_mask: 31
        vlan_id: 60
        peer: SW3
        peer_if: 1/1/8

switch3:
  hostname: 192.168.12.249
  data:
    vlans:
      - id: 130
        name: PC
        members: 1/1/10
        ip: 192.168.130.254/24
    interfaces:
      - name: 1/1/1
        ip_address: 10.0.0.9
        subnet_mask: 31
        vlan_id: 50
        peer: SW2
        peer_if: 1/1/3
      - name: 1/1/8
        ip_address: 10.0.0.11
        subnet_mask: 31
        vlan_id: 60
        peer: SW2
        peer_if: 1/1/4
      - name: 1/1/3
        ip_address: 10.0.0.5
        subnet_mask: 31
        vlan_id: 30
        peer: SW1
        peer_if: 1/1/3
      - name: 1/1/4
        ip_address: 10.0.0.7
        subnet_mask: 31
        vlan_id: 40
        peer: SW1
        peer_if: 1/1/4
